"use client";
import { useEffect, useRef, useState } from "react";

const FEATURES = [
  {
    title: "Proactive blocklist tracking",
    desc: "Be the first to know if your domain is added to a DNSBL such as those offered by Spamhaus, with removal requests generated by Resend.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <circle cx="12" cy="12" r="1.5" stroke="currentColor"/>
        <path clipRule="evenodd" d="M12 2C12.822 2 13.62 2.099 14.385 2.286c-.142.3-.248.62-.313.954C13.407 3.083 12.713 3 12 3c-3.573 0-6.659 2.082-8.113 5.099-.285-.065-.582-.1-.887-.1-.057 0-.113.001-.17.004C4.373 4.47 7.898 2 12 2ZM2.83 15.996C4.373 19.53 7.898 22 12 22c5.523 0 10-4.477 10-10 0-1.825-.49-3.537-1.343-5.01-.25.222-.528.413-.828.568C20.575 8.87 21 10.385 21 12c0 4.97-4.03 9-9 9-3.573 0-6.659-2.082-8.113-5.099-.285.065-.582.1-.887.1-.057 0-.113-.001-.17-.004Z" fill="currentColor" fillRule="evenodd"/>
        <path clipRule="evenodd" d="M12.1 16.999C12.067 17 12.033 17 12 17c-2.761 0-5-2.239-5-5s2.239-5 5-5 5 2.239 5 5c0-1.657-.168-3.182-.45-4.3a5.1 5.1 0 0 1-.49.086c.27 1.097.44 2.58.44 4.214A5.002 5.002 0 0 1 12 18c-.138 0-.275-.005-.41-.014.136.313.24.643.31.986Z" fill="currentColor" fillRule="evenodd"/>
        <circle cx="16.5" cy="15" fill="currentColor" r="1.5"/>
        <circle cx="2.5" cy="12" fill="currentColor" r="1.5"/>
        <circle cx="18" cy="4" fill="currentColor" r="1.5"/>
        <path d="M11.5 10.5V2.5M12.5 13.5V21.5" stroke="currentColor"/>
      </svg>
    ),
  },
  {
    title: "Faster Time to Inbox",
    desc: "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <path clipRule="evenodd" d="M5 9.628V9.62h-.001c.123-.164.227-.344.308-.54l1.654-3.969C7.323 4.558 7.427 4.378 7.55 4.223H5V3.23H17.5C18.617 3.23 19.5 4.113 19.5 5.23v1.3h-1V5.23c0-.607-.448-1.107-1.023-1.131H8.64a4.5 4.5 0 0 1-.13 1.262L6.857 9.38C6.786 9.554 6.682 9.708 6.562 9.843L5 8.628Zm-.5 4.872H8.5m-6-1H3.5v1h-2c-.276 0-.5.224-.5.5v4c0 1.657 1.343 3 3 3h13c1.657 0 3-1.343 3-3v-3.3c0-.198-.04-.394-.115-.577l-1.654-3.97A2.85 2.85 0 0 0 17.5 11h-1V10L8 15.5H2.5Z" fill="currentColor" fillRule="evenodd"/>
        <path d="M15.5 15.5H21.5M2.5 15.5H8.5" stroke="currentColor"/>
        <path clipRule="evenodd" d="M8 15c0 2.21 1.79 4 4 4s4-1.79 4-4h-1c0 1.66-1.34 3-3 3s-3-1.34-3-3H8Z" fill="currentColor" fillRule="evenodd"/>
      </svg>
    ),
  },
  {
    title: "Build confidence with BIMI",
    desc: "Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC — the email equivalent of a checkmark on social media.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <rect height="17" rx="3.5" stroke="currentColor" width="17" x="1.5" y="5.5"/>
        <path d="M4.5 14V10c0-.276.224-.5.5-.5h10c.276 0 .5.224.5.5v4c0 .276-.224.5-.5.5H13.5V16a.5.5 0 0 1-.5.5H11.5V18a.5.5 0 0 1-.5.5H9a.5.5 0 0 1-.5-.5v-1.5H7a.5.5 0 0 1-.5-.5V14.5H5a.5.5 0 0 1-.5-.5Z" stroke="currentColor"/>
        <path d="M6.5 9.5V12M8.5 9.5V12M11.5 9.5V12M13.5 9.5V12" stroke="currentColor"/>
      </svg>
    ),
  },
  {
    title: "Managed Dedicated IPs",
    desc: "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <path d="M8.5 14L8.15 14.35 9 14H8.5ZM11.5 11.5V12H12V11.5H11.5ZM10.5 11.5l-.498.05.048.45H10.5V11.5ZM9 7.29V14H8V7.29H9ZM13 5.5V12H14V5.5H13ZM15 7.5V12H16V7.5H15ZM17 9.5V12.79H18V9.5H17ZM11 5.5V11.5h1V5.5h-1ZM9.57 7.26l.43 4.29 1-.1-.43-4.29-1 .1ZM10.5 12h1v-1h-1v1ZM6.78 15.17l-.43-.71.86-.52.43.71-.86.52ZM6 13.67v-.11H5v.12H6Z" fill="currentColor"/>
        <path d="M11.45 18a4.84 4.84 0 0 1-3.16-1.11L7.66 17.67c1.07.86 2.41 1.33 3.79 1.33V18ZM17 12.79A5.21 5.21 0 0 1 11.79 18v1A6.21 6.21 0 0 0 18 12.79H17ZM16.5 9a.5.5 0 0 1 .5.5H18a1.5 1.5 0 0 0-1.5-1.5V9ZM12.5 5a.5.5 0 0 1 .5.5H14A1.5 1.5 0 0 0 12.5 4V5ZM7.66 12.46a1.56 1.56 0 0 0-1.1-.46V13c.15 0 .29.06.39.16l.71-.7ZM12.5 4A1.5 1.5 0 0 0 11 5.5h1C12 5.22 12.22 5 12.5 5V4ZM8.29 16.89A4.04 4.04 0 0 1 6.79 15.17l-.86.52a5.04 5.04 0 0 0 1.87 2.11l.49-.91Z" fill="currentColor"/>
      </svg>
    ),
  },
  {
    title: "Dynamic suppression list",
    desc: "Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <path d="M12 22.5c1.04 0 2.05-.15 3-.43C19.34 20.77 22.5 16.76 22.5 12c0-.17 0-.34-.01-.5-.01-.17-.02-.33-.04-.5M12 1.5c-1.81 0-3.51.46-5 1.26-1.79.97-3.26 2.45-4.24 4.24-.21.39-.4.79-.56 1.2-.31.79-.52 1.62-.63 2.49C1.53 11.12 1.5 11.56 1.5 12c0 .17 0 .33.01.5.01.17.02.33.04.5M15 1.93c.7.21 1.37.49 2 .83M18.67 3.89c.53.44 1.02.93 1.46 1.46M21.24 7c.34.63.61 1.3.82 2M9 22.07c-.7-.21-1.37-.49-2-.83M5.34 20.12a9.24 9.24 0 0 1-1.46-1.46M2.76 17c-.34-.63-.61-1.3-.82-2" stroke="currentColor"/>
      </svg>
    ),
  },
  {
    title: "IP and domain monitoring",
    desc: "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <rect height="17" rx="3.5" stroke="currentColor" width="21" x="1.5" y="2.5"/>
        <path d="M6 22.5H18" stroke="currentColor"/>
        <circle cx="10" cy="11" r="4.5" stroke="currentColor"/>
        <path d="M11.5 11c0 1.33-.22 2.52-.55 3.35-.17.42-.35.72-.53.91-.18.19-.32.24-.42.24-.1 0-.23-.05-.41-.24-.18-.19-.37-.49-.54-.91C8.72 13.52 8.5 12.33 8.5 11c0-1.33.22-2.52.55-3.35.17-.42.35-.72.53-.91.18-.19.32-.24.42-.24.1 0 .23.05.41.24.18.19.37.49.54.91C11.28 8.48 11.5 9.67 11.5 11Z" stroke="currentColor"/>
        <path d="M5.5 11.5H14.5" stroke="currentColor"/>
        <path d="M18.5 8V12M18.5 13V14" stroke="currentColor"/>
      </svg>
    ),
  },
  {
    title: "Verify DNS records",
    desc: "Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <rect height="17" rx="3.5" stroke="currentColor" width="21" x="1.5" y="2.5"/>
        <path d="M5.5 9l4.92 2.23c.39.18.81.27 1.24.27h.68c.43 0 .85-.09 1.24-.27L18.5 9" stroke="currentColor"/>
        <rect height="9" rx="1.5" stroke="currentColor" width="13" x="5.5" y="7.5"/>
      </svg>
    ),
  },
  {
    title: "Battle-tested infrastructure",
    desc: "Rely on a platform of reputable IPs used by trustworthy senders with distributed workloads across different IP pools.",
    icon: (
      <svg fill="none" height="24" viewBox="0 0 24 24" width="24">
        <path d="M23.5 10V9.9C23.5 7.66 23.5 6.54 23.06 5.68 22.68 4.93 22.07 4.32 21.32 3.94 20.46 3.5 19.34 3.5 17.1 3.5H16M23.5 15C23.5 16.4 23.5 17.09 23.33 17.66 22.94 18.94 21.94 19.94 20.66 20.33 20.09 20.5 19.4 20.5 18 20.5H16M.5 10V9.9C.5 7.66.5 6.54.94 5.68 1.32 4.93 1.93 4.32 2.68 3.94 3.54 3.5 4.66 3.5 6.9 3.5H8M.5 15C.5 16.4.5 17.09.67 17.66 1.06 18.94 2.06 19.94 3.34 20.33 3.91 20.5 4.6 20.5 6 20.5H8" stroke="currentColor" strokeLinejoin="round"/>
        <path d="M7.8 10.7L6.5 12l1.87 1.4c.09.07.19.1.3.1H9.79c.13 0 .26-.05.35-.15L11.5 12l-1.43-.95c-.05-.03-.1-.06-.15-.07L8.28 10.57c-.17-.04-.35.01-.48.13Z" stroke="currentColor" strokeLinejoin="round"/>
        <path d="M13.93 11.05L12.5 12l1.87 1.4c.09.07.19.1.3.1h.67c.11 0 .22-.04.3-.1L17.5 12l-1.3-1.3c-.12-.12-.3-.17-.47-.13L14.08 10.98a.9.9 0 0 0-.15.07Z" stroke="currentColor" strokeLinejoin="round"/>
        <path d="M20.5 12.43V10.22c0-1-.72-1.83-1.7-1.98l-2.83-.44A19.5 19.5 0 0 0 12 7.5c-1.33 0-2.66.1-3.98.3L5.2 8.24c-.98.15-1.7.98-1.7 1.97v2.22c0 1.57.89 3.01 2.3 3.71.46.23.97.35 1.49.35h.45c.51 0 1.01-.1 1.49-.3l.86-.34c.61-.25 1.27-.37 1.93-.37.66 0 1.32.12 1.93.37l.86.34c.48.19.98.3 1.49.3h.44c.52 0 1.03-.12 1.49-.35 1.41-.7 2.3-2.14 2.3-3.71Z" stroke="currentColor"/>
      </svg>
    ),
  },
];

export default function Deliverability() {
  const [visible, setVisible] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setVisible(true); }, { threshold: 0.06 });
    obs.observe(el);
    return () => obs.disconnect();
  }, []);

  return (
    <section ref={ref} className="dl-section">
      {/* Top shimmer */}
      <div aria-hidden className="dl-shimmer" />
      <div aria-hidden className="dl-shimmer-glow" />

      <h2
        className="dl-title"
        style={{ opacity: visible ? 1 : 0, transform: visible ? "none" : "translateY(20px)", transition: "opacity 0.6s ease, transform 0.6s ease" }}
      >
        Reach humans, not spam folders
      </h2>

      <div className="dl-grid">
        {FEATURES.map((f, i) => (
          <div
            key={f.title}
            className="dl-feature"
            style={{
              opacity: visible ? 1 : 0,
              transform: visible ? "none" : "translateY(16px)",
              transition: `opacity 0.5s ease ${i * 0.07}s, transform 0.5s ease ${i * 0.07}s`,
            }}
          >
            <div className="dl-feature-header">
              <span className="dl-feature-icon">{f.icon}</span>
              <h3 className="dl-feature-title">{f.title}</h3>
            </div>
            <p className="dl-feature-desc">{f.desc}</p>
          </div>
        ))}
      </div>

      <style>{`
        .dl-section, .dl-section * { font-family: var(--font-sans, 'Inter', sans-serif); box-sizing: border-box; }
        .dl-section {
          position: relative;
          max-width: 80rem;
          margin: 3rem auto 0;
          overflow: hidden;
          border-radius: 1.5rem;
          border-top: 1px solid rgba(255,255,255,0.09);
          padding: 5rem 2rem 4rem;
        }
        .dl-shimmer {
          position: absolute; left: 50%; right: auto; top: 0;
          width: 300px; height: 1px; max-width: 100%;
          transform: translateX(-50%) translateY(-50%);
          pointer-events: none;
          background: linear-gradient(90deg, transparent 0%, rgba(143,143,143,0.67) 50%, transparent 100%);
        }
        .dl-shimmer-glow {
          position: absolute; left: 50%; top: 0;
          width: 320px; height: 300px;
          transform: translateX(-50%) translateY(-50%);
          pointer-events: none;
          background: conic-gradient(from 90deg at 50% 50%, #00000000 50%, #000 50%), radial-gradient(rgba(200,200,200,0.1) 0%, transparent 80%);
        }

        .dl-title {
          font-size: clamp(2.5rem, 5vw, 3.5rem);
          font-weight: 400;
          letter-spacing: -0.04em;
          line-height: 1.18;
          color: #fff;
          margin: 0 0 3rem;
          max-width: 14ch;
          position: relative; z-index: 2;
          background: linear-gradient(to bottom, #fff 50%, rgba(255,255,255,0.55) 100%);
          -webkit-background-clip: text; background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .dl-grid {
          display: grid;
          grid-template-columns: 1fr;
          gap: 2.5rem 3rem;
          position: relative; z-index: 2;
        }
        @media (min-width: 540px)  { .dl-grid { grid-template-columns: repeat(2, 1fr); } }
        @media (min-width: 1024px) { .dl-grid { grid-template-columns: repeat(3, 1fr); } }

        .dl-feature { display: flex; flex-direction: column; gap: 0.625rem; }
        .dl-feature-header { display: flex; flex-direction: row; align-items: center; gap: 0.75rem; margin-bottom: 0.25rem; }
        @media (min-width: 768px) { .dl-feature-header { flex-direction: column; align-items: flex-start; gap: 1rem; } }
        .dl-feature-icon { color: rgba(255,255,255,0.7); flex-shrink: 0; }
        .dl-feature-title { font-size: 1.0625rem; font-weight: 400; letter-spacing: -0.02em; color: #fff; margin: 0; line-height: 1.3; }
        .dl-feature-desc { font-size: 0.8125rem; line-height: 1.65; color: rgba(255,255,255,0.42); margin: 0; }

        @media (max-width: 640px) { .dl-section { padding: 3rem 1.25rem; border-radius: 1rem; } .dl-title { font-size: 2.25rem; } }
      `}</style>
    </section>
  );
}
